services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ci-cd
      - POSTGRES_PASSWORD=secretpassword

  backend:
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        - DATABASE_URL=$DATABASE_URL
    ports:
      - 4000:3000
    depends_on:
      - postgres
