name: CI for backend app

on:
  push:
    branches: ["backend"]

jobs:

  Continuous-Integration:

    name: Runs the tests for the backend app
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup bun
        run: npm install -g bun

      - name: install deps
        run: bun install

      - name: run tests
        run: bun run test